drop table if exists processado.d_resultado_selo_verde_2_1;

select
	last_execution as dat_execucao,
	soja_ha as area_soja_ha,
	ind_status_imovel as tx_status_imovel,
	cod_imovel as tx_cod_imovel,
	tipo_imove as tx_tipo_imovel,
	nom_munici as tx_nome_municipio,
	geocodigo as id_municipio,
	car_area as area_calc_ir,
	cf_n_mf as num_modulo_fiscal,
	cf_tot_conv as area_cf_tot_conv,
	cf_tot_veg as area_cf_tot_veg,
	cf_app_rest_d as area_cf_app_rest_d,
	cf_cra_rl as area_cf_cra_rl,
	cf_rl_deficit as area_cf_rl_deficit,
	cf_d_pos08 as area_cf_d_pos08,
	cf_d_pos08_il as area_cf_d_pos08_il,
	cod_over_car as tx_cod_imovel_over_car,
	cod_over_assentamento as tx_cod_over_assentamento,
	sirflor as tx_sirflor,
	cod_over_ti as tx_cod_over_ti,
	perc_over_ti as perc_over_ti ,
	cod_over_quilombola as tx_cod_over_quilombola,
	perc_over_quilombola as perc_over_quilombola  ,
	cod_over_protecao_integral as tx_cod_over_protecao_integral ,
	perc_over_protecao_integral as perc_over_protecao_integral ,
	cod_over_uso_sustentavel as tx_cod_over_uso_sustentavel ,
	perc_over_uso_sustentavel as perc_over_uso_sustentavel,
	ai_ibama_count_autos as qtd_ai_ibama_count_autos ,
	ai_ibama_identificador as qtd_ai_ibama_identificador ,
	ai_ibama_quality as qtd_ai_ibama_quality ,
	emb_ibama_count_emb_flora_ou_uc as qtd_emb_ibama_count_emb_flora_ou_uc ,
	emb_ibama_id_emb_flora_ou_uc as qtd_emb_ibama_id_emb_flora_ou_uc ,
	emb_ibama_quality as qtd_emb_ibama_quality ,
	emb_ibama_dat_desemb_flora_uc_s as qtd_emb_ibama_dat_desemb_flora_uc_s ,
	emb_ibama_id_desemb_flora_uc_s as qtd_emb_ibama_id_desemb_flora_uc_s ,
	apr_semas_count_apreensao_flora as qtd_apr_semas_count_apreensao_flora,
	destr_semas_id_flora as tx_destr_semas_id_flora,
	destr_semas_count_destruicao_flora as qtd_destr_semas_count_destruicao_flora ,
	emb_semas_id_emb_flora as tx_emb_semas_id_emb_flora ,
	emb_semas_count_emb_flora as tx_emb_semas_count_emb_flora ,
	ai_semas_count_flora as qtd_ai_semas_count_flora ,
	ai_semas_id_flora as tx_ai_semas_id_flora ,
	emb_icmbio_count as qtd_emb_icmbio_count,
	emb_icmbio_quality as qtd_emb_icmbio_quality ,
	emb_icmbio_id as tx_emb_icmbio_id ,
	emb_icmbio_certeza as tx_emb_icmbio_certeza ,
	trabalho_escravo_id as tx_trabalho_escravo_id ,
	trabalho_escravo_quality as qtd_trabalho_escravo_quality ,
	rastreab_nivel_contaminacao as tx_rastreab_nivel_contaminacao ,
	situacao as tx_situacao ,
	condicao_i as tx_condicao_i ,
	prop_ignored as tx_prop_ignored ,
	contestacao as tx_contestacao ,
	asv_ibama_count as qtd_asv_ibama_count,
	asv_ibama_ids as tx_asv_ibama_ids ,
	asv_ibama_quality as qtd_asv_ibama_quality ,
	asv_semas_count as qtd_asv_semas_count ,
	asv_semas_ids as tx_asv_semas_ids ,
	asv_semas_quality as qtd_asv_semas_quality ,
	lar_semas_count as qtd_lar_semas_count ,
	lar_semas_ids as tx_lar_semas_ids ,
	lar_semas_quality as qtd_lar_semas_quality ,
	rastreab_percent_contamin as tx_rastreab_percent_contamin ,
	rast_check_found as tx_rast_check_found,
	perc_fornecedores_contamin as perc_fornecedores_contamin ,
	perc_fornecedores_contamin_n1 as perc_fornecedores_contamin_n1 ,
	sellercar_contaminado_diretamente as tx_sellercar_contaminado_diretamente
into processado.d_resultado_selo_verde_2_1
from
	bruto.selo_verde_resultados_integrados_selo_verde_2_0;